### PR TITLE
Fixed an issue with colliding slugs when modifying a project

### LINKED ISSUE #561: Project slug collides issue on modification request
### Describe the bug

The collision check on projects will error out if you send a modify request with the slug of the project you are changing!

### Steps to reproduce

1. Make project (slug: example)
2. Send modify request to project containing slug example in it
3. Errors out

### Expected behavior

The slug of the project remains unchanged

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by masecla22**
Fixes #561. 

Covered by Modrinth4J test cases at 
https://github.com/masecla22/Modrinth4J/blob/master/src/test/java/masecla/modrinth4j/client/ProjectEndpointsTests.java#L302-L316

### CODE REVIEW

File: src/routes/projects.rs [hunk 1]
```diff
@@ -893,11 +893,13 @@ pub async fn project_edit(
                 }
 
                 {
```
Comment (triphora) [inline src/routes/projects.rs:895]: Wouldn't it be better to do the check here in code instead of in the query? We can bypass this entirely if the new slug is the same as the old slug.

Comment (masecla22) [reply src/routes/projects.rs:895]: It may just be my unfamiliarity with the code, though I didn't see anything in that scope that would allow me to check the _current_ slug of the project without an additional query.

Comment (triphora) [reply src/routes/projects.rs:895]: `project_item` is the current project

**Review by triphora — APPROVED** [review]

**Review by triphora — APPROVED** [review]

**Comment by triphora** [comment]
..why did I rereview that?

**Review by Geometrically — APPROVED** [review]

**Comment by masecla22** [comment]
> ..why did I rereview that?

No clue
